### ISSUE TITLE
Issue loading library

### ISSUE THREAD

**Issue by i-shah** [shapiromatron/bmds-archive#5]
Successfully installed on Ubuntu 18.10:-
```
Successfully installed bmds-0.10.0 python-docx-0.8.7 simple-settings-0.13.0
```
This is what I get on loading the library:-

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bmds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bmds/__init__.py", line 6, in <module>
    from .session import * # noqa
  File "/usr/local/lib/python2.7/dist-packages/bmds/session.py", line 126
    async def execute_models(self):
            ^
SyntaxError: invalid syntax

```
Any ideas?

**Comment by i-shah** [comment]
RTFM - doesn't work with python2, only python3. Pls ignore.
